name: Build and Deploy
on:
    push:
        branches: ["main"]

permissions:
    contents: write
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Node
              uses: actions/setup-node@v1
              with:
                  node-version: "14"

            - name: Install and Build
              run: |
                  echo "${{ secrets.NPMRC_TOKEN }}" > .npmrc
                  npm install
                  npm run releases

            - name: github pages
              uses: crazy-max/ghaction-github-pages@v3.0.0
              with:
                  build_dir: build
              env:
                  GITHUB_TOKE: ${{ secrets.NPMRC_TOKEN }}
