name: library
on:
    push:
        branches: main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: check code
              uses: actions/checkout@v3

            - name: publish to github package
              uses: elgohr/Publish-Docker-Github-Action@v4
              with:
                  name: speech-to-text
                  username: ${{ github.actor }}
                  password: ${{ secrets.MY_TOKEN }}
                  registry: ghcr.io
                  dockerfile: Dockerfile

            - name: github pages
              uses: crazy-max/ghaction-github-pages@v3.0.0
              with:
                  build_dir: build
