name: library
on:
    push:
        branches: main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: check code
              uses: actions/checkout@v3
              with:
                  repository: szkj-web-he/speech-to-text
                  ref: main

            - name: Install and Build
              run: |
                  echo "${{ secrets.NPMRC_TOKEN }}" > .npmrc
                  npm install
                  npm run releases

            - name: github pages
              uses: JamesIves/github-pages-deploy-action@4.0.0
              with:
                  token: ${{ secrets.NPMRC_TOKEN }}
                  folder: build
