name: library
on:
    push:
        branches: main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: check code
              uses: actions/checkout@v3

            - name: Install and Build
              run: |
                  echo "${{ secrets.NPMRC_TOKEN }}" > .npmrc
                  npm install
                  npm run releases

            - name: github pages
              uses: crazy-max/ghaction-github-pages@v3.0.0
              with:
                  build_dir: build
